"use client";

import { useEffect, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  ArrowUpRight, Bookmark, Check, ChevronRight, CircleHelp, ExternalLink,
  FileText, GitBranch, Inbox, Layers3, Menu, MessageSquareText, MoreHorizontal,
  Newspaper, Search, Settings2, ShieldCheck, Sparkles, Tag, X, Zap,
} from "lucide-react";

type View = "for-you" | "tech-feed" | "research" | "github" | "solutions";
type Signal = {
  id: string; title: string; summary: string; source: string; sourceType: string;
  time: string; kind: string; score: number; tags: string[]; why: string;
  action: string; url: string; saved?: boolean;
};

const PROFILE_KEY = "signalstack-profile";
const initialTopics = ["AI agents", "RAG", "Python", "Vector search", "Web apps"];
const seedSignals: Signal[] = [
  { id: "agent-checkpoints", title: "Reliable checkpoints for long-running agent workflows", summary: "An open-source workflow pattern adds recoverable state and retry handling for multi-step agent tasks.", source: "GitHub", sourceType: "github", time: "2h ago", kind: "Open source", score: 94, tags: ["AI agents", "Python", "Reliability"], why: "You work with Python and agent workflows. Checkpointed state is a direct answer to the reliability gap in your current profile.", action: "Compare its checkpoint model with your orchestration layer, then test a failed-step recovery path.", url: "https://github.com/" },
  { id: "retrieval-eval", title: "Evaluation-driven retrieval for technical RAG", summary: "A research approach measures retrieval quality before generation, revealing weak evidence earlier in the pipeline.", source: "arXiv", sourceType: "research", time: "5h ago", kind: "Research", score: 91, tags: ["RAG", "Vector search", "Evaluation"], why: "SignalStack needs accurate semantic matching and transparent recommendations, so retrieval evaluation is foundational to your product.", action: "Turn precision@k and evidence coverage into a small offline benchmark before changing the ranker.", url: "https://arxiv.org/" },
  { id: "feed-dedup", title: "How an engineering team kept a high-volume feed fresh without duplicates", summary: "The team combined canonical URLs, content fingerprints, and freshness windows to prevent duplicate updates.", source: "Engineering blog", sourceType: "engineering", time: "Yesterday", kind: "Case study", score: 88, tags: ["Python", "PostgreSQL", "Ingestion"], why: "It addresses the same ingestion and deduplication problem SignalStack faces as it normalizes multiple technical sources.", action: "Start with canonical URLs and text fingerprints, then log every merge decision for later ranking feedback.", url: "https://martinfowler.com/" },
  { id: "hybrid-search", title: "Hybrid search improves technical-document retrieval", summary: "Exact keyword matching keeps technology names precise while vector similarity finds conceptually related material.", source: "pgvector release notes", sourceType: "release", time: "Yesterday", kind: "Release", score: 85, tags: ["Vector search", "PostgreSQL", "RAG"], why: "Your feed combines exact technologies with fuzzy problem areas; hybrid retrieval is the bridge between both signals.", action: "Add metadata filters for source type, date, and credibility before tuning vector weights.", url: "https://github.com/pgvector/pgvector" },
  { id: "observability", title: "Tracing patterns for production AI applications", summary: "A practical guide maps retrieval, tool calls, and model output into one trace so failures can be explained.", source: "OpenTelemetry", sourceType: "engineering", time: "2d ago", kind: "Engineering", score: 82, tags: ["AI agents", "Observability", "Web apps"], why: "You are building a source-backed product where latency and evidence coverage matter as much as the final answer.", action: "Instrument retrieval latency and source coverage before adding more model-generated explanation.", url: "https://opentelemetry.io/" },
];
const researchItems = [
  { label: "RESEARCH NOTE", title: "Evaluation-driven retrieval for technical RAG", problem: "How do you catch weak evidence before an answer sounds convincing?", method: "A benchmark separates retrieval quality from generation quality and tests evidence coverage at k=5 and k=10.", limitation: "The benchmark uses curated corpora, so results may shift on live engineering feeds.", practical: "High — the evaluation shape can become a local regression test for SignalStack.", tag: "RAG", url: "https://arxiv.org/" },
  { label: "RESEARCH NOTE", title: "Structured memory for tool-using agents", problem: "How should long-running agents preserve state without bloating every prompt?", method: "The system stores compact task state and retrieves only the relevant working set at each step.", limitation: "The paper leaves operational cost under realistic multi-tenant loads open.", practical: "Medium — useful as a design pattern, not a drop-in architecture.", tag: "Agents", url: "https://arxiv.org/" },
];
const githubItems = [
  { repo: "pgvector/pgvector", description: "Open-source vector similarity search for Postgres.", language: "C / SQL", stars: "15.8k", activity: "Released 3 days ago", match: "Your PostgreSQL + RAG stack", url: "https://github.com/pgvector/pgvector" },
  { repo: "open-telemetry/opentelemetry-demo", description: "A vendor-neutral microservice demo for tracing real systems.", language: "Go / TypeScript", stars: "3.1k", activity: "Updated yesterday", match: "Your observability focus", url: "https://github.com/open-telemetry/opentelemetry-demo" },
  { repo: "langchain-ai/langgraph", description: "Build resilient, stateful orchestration for agentic applications.", language: "Python", stars: "20.4k", activity: "Release v0.6.4", match: "Your AI agent workflows", url: "https://github.com/langchain-ai/langgraph" },
];
const onboardingSchema = z.object({ github: z.string().optional(), interests: z.string().min(3, "Add at least one technical interest.") });
type OnboardingValues = z.infer<typeof onboardingSchema>;

function sourceIcon(type: string) {
  if (type === "github") return <GitBranch size={14} />;
  if (type === "research") return <FileText size={14} />;
  if (type === "release") return <Zap size={14} />;
  return <Newspaper size={14} />;
}

export default function Home() {
  const [view, setView] = useState<View>("for-you");
  const [profileReady, setProfileReady] = useState(false);
  const [profile, setProfile] = useState<{ skills: string[]; projects: string[]; topics: string[]; github?: string; resume?: string } | null>(null);
  const [resumeFile, setResumeFile] = useState<File | null>(null);
  const [inferred, setInferred] = useState<{ skills: string[]; projects: string[]; topics: string[] } | null>(null);
  const [building, setBuilding] = useState(false);
  const [signals, setSignals] = useState(seedSignals);
  const [filter, setFilter] = useState("All signals");
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<Signal | null>(null);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<{ text: string; sources: Array<{ title: string; source: string; url: string }> } | null>(null);
  const [asking, setAsking] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [notice, setNotice] = useState("");
  const form = useForm<OnboardingValues>({ resolver: zodResolver(onboardingSchema), defaultValues: { github: "", interests: initialTopics.join(", ") } });

  useEffect(() => { const stored = window.localStorage.getItem(PROFILE_KEY); if (stored) { setProfile(JSON.parse(stored)); setProfileReady(true); } }, []);
  const activeTopics = profile?.topics?.length ? profile.topics : initialTopics;
  const filteredSignals = useMemo(() => { const q = search.toLowerCase(); return signals.filter((signal) => { const filterMatch = filter === "All signals" || (filter === "saved" ? Boolean(signal.saved) : signal.sourceType === filter); const searchMatch = !q || `${signal.title} ${signal.summary} ${signal.tags.join(" ")}`.toLowerCase().includes(q); return filterMatch && searchMatch; }); }, [filter, search, signals]);

  async function analyzeResume() {
    if (!resumeFile) return null;
    const body = new FormData(); body.append("file", resumeFile);
    try { const response = await fetch("http://127.0.0.1:8000/profile/resume", { method: "POST", body }); if (!response.ok) return null; const data = await response.json(); return data.analysis as { skills: string[]; projects: string[]; suggested_topics: string[] }; } catch { return null; }
  }
  async function previewProfile(values: OnboardingValues) {
    setBuilding(true); const analysis = await analyzeResume(); const typedTopics = values.interests.split(",").map((item) => item.trim()).filter(Boolean);
    setInferred({ skills: analysis?.skills?.length ? analysis.skills : typedTopics, projects: analysis?.projects ?? [], topics: Array.from(new Set([...typedTopics, ...(analysis?.suggested_topics ?? []).slice(0, 4)])) }); setBuilding(false);
  }
  async function buildProfile(values: OnboardingValues) {
    setBuilding(true); const analysis = await analyzeResume(); const typedTopics = values.interests.split(",").map((item) => item.trim()).filter(Boolean); const next = { skills: analysis?.skills ?? typedTopics, projects: analysis?.projects ?? [], topics: Array.from(new Set([...typedTopics, ...(analysis?.suggested_topics ?? []).slice(0, 4)])), github: values.github?.trim().replace(/^@/, ""), resume: resumeFile?.name };
    window.localStorage.setItem(PROFILE_KEY, JSON.stringify(next)); setProfile(next); setInferred(null); setProfileReady(true); setBuilding(false);
  }
  async function askSignalStack() {
    if (!question.trim()) return; setAsking(true);
    try { const response = await fetch("http://127.0.0.1:8000/rag/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, profile: { topics: activeTopics, skills: profile?.skills ?? activeTopics, projects: profile?.projects ?? [] } }) }); const data = await response.json(); setAnswer({ text: response.ok ? data.answer : data.detail ?? "The local research service is unavailable.", sources: response.ok ? data.sources ?? [] : [] }); } catch { setAnswer({ text: "I couldn’t reach the local retrieval service. Start the FastAPI service on port 8000 and try again.", sources: [] }); } setAsking(false);
  }
  function toggleSave(id: string) { setSignals((current) => current.map((signal) => signal.id === id ? { ...signal, saved: !signal.saved } : signal)); setNotice("Saved to your collection"); window.setTimeout(() => setNotice(""), 1800); }
  function markNotRelevant(id: string) { setSignals((current) => current.filter((signal) => signal.id !== id)); setNotice("Removed from your briefing"); window.setTimeout(() => setNotice(""), 1800); }

  if (!profileReady) return <Onboarding form={form} resumeFile={resumeFile} setResumeFile={setResumeFile} inferred={inferred} building={building} onPreview={previewProfile} onSave={buildProfile} />;
  return <main className="app-shell">
    <aside className={`sidebar ${mobileNav ? "mobile-open" : ""}`}>
      <div className="side-brand"><span className="brand-mark">S</span><span>SignalStack</span><span className="beta-pill">LOCAL</span></div>
      <div className="workspace-label">YOUR WORKSPACE</div>
      <nav className="side-nav"><NavItem active={view === "for-you"} icon={<Sparkles size={17} />} label="For You" badge="12" onClick={() => { setView("for-you"); setMobileNav(false); }} /><NavItem active={view === "tech-feed"} icon={<Inbox size={17} />} label="Tech Feed" onClick={() => { setView("tech-feed"); setMobileNav(false); }} /><NavItem active={view === "research"} icon={<FileText size={17} />} label="Research" onClick={() => { setView("research"); setMobileNav(false); }} /><NavItem active={view === "github"} icon={<GitBranch size={17} />} label="GitHub Radar" badge="4" onClick={() => { setView("github"); setMobileNav(false); }} /><NavItem active={view === "solutions"} icon={<Layers3 size={17} />} label="Real solutions" onClick={() => { setView("solutions"); setMobileNav(false); }} /></nav>
      <div className="workspace-label side-lower">PERSONALIZE</div>
      <nav className="side-nav"><NavItem icon={<Bookmark size={17} />} label="Saved" badge={String(signals.filter((signal) => signal.saved).length)} onClick={() => { setFilter("saved"); setView("for-you"); setMobileNav(false); }} /><NavItem icon={<Tag size={17} />} label="Topics" onClick={() => { setFilter("All signals"); setView("for-you"); setMobileNav(false); }} /></nav>
      <div className="sidebar-bottom"><div className="source-status"><span className="status-dot" />Sources healthy <span className="status-count">16</span></div><button className="profile-mini" onClick={() => { window.localStorage.removeItem(PROFILE_KEY); setProfileReady(false); }}><span className="avatar">M</span><span><b>{profile?.github || "Local profile"}</b><small>Personal workspace</small></span><MoreHorizontal size={16} /></button></div>
    </aside>
    <section className="main-column"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14} /><b>{viewTitle(view)}</b></div><div className="topbar-actions"><button className="icon-button" aria-label="Search"><Search size={18} /></button><button className="help-button"><CircleHelp size={16} /> Help</button><span className="topbar-avatar">M</span></div></header><div className="content-wrap">
      {view === "for-you" && <ForYouView signals={filteredSignals} activeTopics={activeTopics} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} onSelect={setSelected} onSave={toggleSave} onDismiss={markNotRelevant} />}
      {view === "tech-feed" && <TechFeed signals={filteredSignals} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} onSelect={setSelected} onSave={toggleSave} onDismiss={markNotRelevant} />}
      {view === "research" && <ResearchView onSelect={(item) => setSelected({ ...seedSignals[1], title: item.title, summary: item.method, tags: [item.tag], url: item.url })} />}
      {view === "github" && <GithubView github={profile?.github} />}
      {view === "solutions" && <SolutionsView />}
    </div></section>
    {selected && <SignalDetail signal={selected} onClose={() => setSelected(null)} onSave={() => toggleSave(selected.id)} />}
    {notice && <div className="toast"><Check size={16} /> {notice}</div>}
    <AskDock question={question} setQuestion={setQuestion} answer={answer} asking={asking} onAsk={askSignalStack} />
  </main>;
}

function NavItem({ active, icon, label, badge, onClick }: { active?: boolean; icon: React.ReactNode; label: string; badge?: string; onClick: () => void }) { return <button className={`nav-item ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span>{badge && <small>{badge}</small>}</button>; }
function viewTitle(view: View) { return { "for-you": "For You", "tech-feed": "Tech Feed", research: "Research", github: "GitHub Radar", solutions: "Real solutions" }[view]; }

function Onboarding({ form, resumeFile, setResumeFile, inferred, building, onPreview, onSave }: { form: ReturnType<typeof useForm<OnboardingValues>>; resumeFile: File | null; setResumeFile: (file: File | null) => void; inferred: { skills: string[]; projects: string[]; topics: string[] } | null; building: boolean; onPreview: (values: OnboardingValues) => void; onSave: (values: OnboardingValues) => void }) {
  return <main className="onboarding-page"><div className="onboarding-grid"><div className="onboarding-brand"><div className="side-brand"><span className="brand-mark">S</span><span>SignalStack</span><span className="beta-pill">LOCAL MVP</span></div><div className="onboarding-intro"><div className="eyebrow"><span className="status-dot" /> Private technical intelligence</div><h1>Make the feed<br /><em>earn your attention.</em></h1><p>SignalStack connects the technical work you already do with the updates worth knowing. Start with the context that makes your signals yours.</p><div className="proof-row"><span><ShieldCheck size={16} /> Your data stays local</span><span><Zap size={16} /> Explainable by default</span></div></div><div className="onboarding-foot">Built for engineers, researchers, and technical builders.</div></div><section className="onboarding-panel"><div className="panel-kicker">01 / YOUR CONTEXT</div><h2>Give SignalStack a starting point.</h2><p className="panel-copy">We’ll show you exactly what we infer before creating your briefing. Nothing is hidden or permanent.</p><form onSubmit={form.handleSubmit(inferred ? onSave : onPreview)}><label className="upload-box"><input type="file" accept=".pdf,.docx,.txt" onChange={(event) => setResumeFile(event.target.files?.[0] ?? null)} /><span className="upload-icon"><FileText size={20} /></span><span><b>{resumeFile ? resumeFile.name : "Drop your resume here"}</b><small>{resumeFile ? "Ready to analyze locally" : "PDF, DOCX, or TXT · optional"}</small></span><ArrowUpRight size={18} /></label><label className="input-label">Public GitHub username <span>OPTIONAL</span><div className="input-with-icon"><GitBranch size={17} /><input {...form.register("github")} placeholder="your-username" /></div></label><label className="input-label">What are you working on right now?<div className="input-with-icon textarea-wrap"><Tag size={17} /><textarea {...form.register("interests")} placeholder="AI agents, Python, RAG, vector search" /></div></label>{form.formState.errors.interests && <p className="form-error">{form.formState.errors.interests.message}</p>}{inferred && <InferencePreview inferred={inferred} />}{inferred ? <button className="primary-button" type="submit" disabled={building}>{building ? "Saving profile…" : "Looks right — build my briefing"}<ChevronRight size={17} /></button> : <button className="primary-button" type="submit" disabled={building}>{building ? "Reading your context…" : "Preview my signal profile"}<ChevronRight size={17} /></button>}</form><p className="privacy-note"><ShieldCheck size={15} /> Resume analysis runs through your local API. You can edit or delete this profile anytime.</p></section></div></main>;
}
function InferencePreview({ inferred }: { inferred: { skills: string[]; projects: string[]; topics: string[] } }) { const groups = [{ label: "SKILLS", values: inferred.skills.slice(0, 8) }, { label: "PROJECT SIGNALS", values: inferred.projects.slice(0, 3) }, { label: "TOPICS TO WATCH", values: inferred.topics.slice(0, 8) }]; return <div className="inference-preview"><div className="inference-heading"><span><Sparkles size={15} /> INFERRED FROM YOUR CONTEXT</span><b>Review before saving</b></div>{groups.map((group) => <div className="inference-group" key={group.label}><span>{group.label}</span><div>{group.values.length ? group.values.map((value) => <button type="button" key={value}>{value}<X size={11} /></button>) : <i>Nothing detected yet</i>}</div></div>)}</div>; }
function WorkspaceHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) { return <div className="workspace-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{actions}</div>; }

function ForYouView({ signals, activeTopics, filter, setFilter, search, setSearch, onSelect, onSave, onDismiss }: { signals: Signal[]; activeTopics: string[]; filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; onSelect: (signal: Signal) => void; onSave: (id: string) => void; onDismiss: (id: string) => void }) { return <><WorkspaceHeader eyebrow="PERSONAL BRIEFING · UPDATED 8 MIN AGO" title="The signal, not the noise." description="A high-confidence read on the technical changes closest to your work." actions={<div className="quality-score"><span>PROFILE FIT</span><b>94</b><small>/ 100</small></div>} /><div className="focus-strip"><div className="focus-title"><Sparkles size={16} /> Using your focus</div><div className="focus-tags">{activeTopics.slice(0, 6).map((topic) => <span key={topic}>{topic}</span>)}</div><button>Edit profile <ArrowUpRight size={14} /></button></div><FeedToolbar filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} tabs={["All signals", "github", "research", "engineering", "release"]} /><div className="feed-heading"><div><h2>Recommended for you <span>{signals.length}</span></h2><p>Ranked by profile overlap, source quality, freshness, and your feedback.</p></div><button className="sort-button">Freshest first <ChevronRight size={14} /></button></div><div className="signal-list">{signals.map((signal) => <SignalCard key={signal.id} signal={signal} onSelect={onSelect} onSave={onSave} onDismiss={onDismiss} />)}{!signals.length && <EmptyState />}</div></>; }
function TechFeed({ signals, filter, setFilter, search, setSearch, onSelect, onSave, onDismiss }: { signals: Signal[]; filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; onSelect: (signal: Signal) => void; onSave: (id: string) => void; onDismiss: (id: string) => void }) { return <><WorkspaceHeader eyebrow="THE TECH FEED · 16 SOURCES" title="Everything technical, curated." description="A broader view across primary sources, research, releases, and engineering stories." actions={<button className="outline-button"><Settings2 size={15} /> Source settings</button>} /><FeedToolbar filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} tabs={["All signals", "github", "research", "engineering", "release"]} /><div className="feed-heading"><div><h2>Latest technical updates <span>{signals.length}</span></h2><p>Primary sources are weighted above commentary and community signals.</p></div></div><div className="signal-list">{signals.map((signal) => <SignalCard key={signal.id} signal={signal} compact onSelect={onSelect} onSave={onSave} onDismiss={onDismiss} />)}</div></>; }
function FeedToolbar({ filter, setFilter, search, setSearch, tabs }: { filter: string; setFilter: (value: string) => void; search: string; setSearch: (value: string) => void; tabs: string[] }) { return <div className="feed-toolbar"><div className="filter-tabs">{tabs.map((tab) => <button key={tab} className={filter === tab ? "active" : ""} onClick={() => setFilter(tab)}>{tab === "All signals" ? tab : tab.charAt(0).toUpperCase() + tab.slice(1)}</button>)}</div><label className="search-box"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search your signals" /></label></div>; }
function SignalCard({ signal, compact, onSelect, onSave, onDismiss }: { signal: Signal; compact?: boolean; onSelect: (signal: Signal) => void; onSave: (id: string) => void; onDismiss: (id: string) => void }) { return <article className={`signal-card ${compact ? "compact" : ""}`}><div className="signal-top"><span className={`source-badge ${signal.sourceType}`}>{sourceIcon(signal.sourceType)} {signal.kind}</span><span className="signal-time">{signal.source} · {signal.time}</span><button className="more-button" aria-label="More actions"><MoreHorizontal size={17} /></button></div><div className="signal-body"><div className="signal-main"><h3>{signal.title}</h3><p>{signal.summary}</p><div className="tag-row">{signal.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div><div className="match-score"><b>{signal.score}</b><span>match</span></div></div><div className="signal-why"><div className="why-icon"><Sparkles size={15} /></div><div><b>Why you&apos;re seeing this</b><p>{signal.why}</p></div></div><div className="signal-footer"><button onClick={() => onSelect(signal)}>View reasoning <ChevronRight size={14} /></button><a href={signal.url} target="_blank" rel="noreferrer">Original source <ExternalLink size={13} /></a><span className="footer-spacer" /><button onClick={() => onDismiss(signal.id)} className="quiet-action">Not relevant</button><button onClick={() => onSave(signal.id)} className={`save-button ${signal.saved ? "saved" : ""}`}><Bookmark size={14} fill={signal.saved ? "currentColor" : "none"} /> {signal.saved ? "Saved" : "Save"}</button></div></article>; }
function EmptyState() { return <div className="empty-state"><Sparkles size={24} /><h3>No signals in this view</h3><p>Try broadening your search or adding another topic to your profile.</p></div>; }

function ResearchView({ onSelect }: { onSelect: (item: typeof researchItems[number]) => void }) { return <><WorkspaceHeader eyebrow="RESEARCH · OPEN PAPERS" title="Ideas with evidence." description="Read the problem, method, limitations, and practical value before you invest the time." actions={<button className="outline-button"><Search size={15} /> Search papers</button>} /><div className="research-grid">{researchItems.map((item) => <article className="research-card" key={item.title}><div className="research-card-top"><span>{item.label}</span><span className="research-topic">{item.tag}</span></div><h3>{item.title}</h3><div className="research-section"><b>THE PROBLEM</b><p>{item.problem}</p></div><div className="research-section"><b>THE METHOD</b><p>{item.method}</p></div><div className="research-footer"><span><ShieldCheck size={14} /> Practical value: {item.practical}</span><button onClick={() => onSelect(item)}>Read reasoning <ChevronRight size={14} /></button></div><div className="limitations"><b>LIMITATION</b><span>{item.limitation}</span></div></article>)}</div></>; }
function GithubView({ github }: { github?: string }) { return <><WorkspaceHeader eyebrow="GITHUB RADAR · PUBLIC ACTIVITY" title="The repos worth watching." description={github ? `Signals enriched around ${github}'s public work and your tracked technologies.` : "Relevant repositories, releases, and public activity around your technical focus."} actions={<button className="outline-button"><GitBranch size={15} /> Connect username</button>} /><div className="radar-summary"><div><span className="radar-label">TRACKED REPOSITORIES</span><b>24</b><small>across 5 technologies</small></div><div><span className="radar-label">RECENT RELEASES</span><b>4</b><small>since your last visit</small></div><div><span className="radar-label">LANGUAGES IN PROFILE</span><b>Python · TS</b><small>from resume + GitHub</small></div></div><div className="section-heading"><div><h2>Relevant public activity</h2><p>Matched to your skills, repositories, and problem areas.</p></div><button className="sort-button">Recent activity <ChevronRight size={14} /></button></div><div className="repo-list">{githubItems.map((repo) => <a className="repo-card" href={repo.url} target="_blank" rel="noreferrer" key={repo.repo}><div className="repo-icon"><GitBranch size={19} /></div><div className="repo-content"><div className="repo-title"><h3>{repo.repo}</h3><ExternalLink size={14} /></div><p>{repo.description}</p><div className="repo-meta"><span>{repo.language}</span><span>★ {repo.stars}</span><span>{repo.activity}</span></div></div><div className="repo-match"><Sparkles size={14} /> {repo.match}</div></a>)}</div></>; }
function SolutionsView() { return <><WorkspaceHeader eyebrow="REAL PROBLEMS, REAL SOLUTIONS" title="Patterns from the field." description="Technical case studies structured for reuse: problem, approach, stack, trade-offs, and outcome." actions={<button className="outline-button"><Search size={15} /> Find a solution</button>} /><article className="solution-card"><div className="solution-aside"><span className="solution-number">01</span><span className="solution-type">CASE STUDY</span><a href="https://martinfowler.com/" target="_blank" rel="noreferrer">Original source <ExternalLink size={13} /></a></div><div className="solution-content"><div className="solution-tags"><span>Ingestion</span><span>PostgreSQL</span><span>Reliability</span></div><h2>How an engineering team kept a high-volume feed fresh without duplicates</h2><div className="solution-grid"><SolutionPart label="THE PROBLEM" value="Multiple source adapters reported the same event with different titles, timestamps, and URLs." /><SolutionPart label="THE APPROACH" value="Normalize canonical URLs, fingerprint content, and apply a source-specific freshness window before ranking." /><SolutionPart label="THE STACK" value="Python · PostgreSQL · scheduled workers · content fingerprints" /><SolutionPart label="THE TRADE-OFF" value="A review queue keeps low-confidence merges visible, but adds operational work." /><SolutionPart label="THE OUTCOME" value="Fewer duplicate interruptions and a traceable decision for every merge." /><SolutionPart label="WHY IT MATCHES YOU" value="SignalStack faces the same problem as it combines GitHub, research, and engineering sources." /></div><div className="solution-action"><button>Save pattern <Bookmark size={14} /></button><span>Source-backed summary · confidence 88%</span></div></div></article></>; }
function SolutionPart({ label, value }: { label: string; value: string }) { return <div><b>{label}</b><p>{value}</p></div>; }

function SignalDetail({ signal, onClose, onSave }: { signal: Signal; onClose: () => void; onSave: () => void }) { return <div className="modal-overlay" onClick={onClose}><section className="detail-modal" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={onClose} aria-label="Close"><X size={18} /></button><div className="eyebrow">EXPLAINED RECOMMENDATION</div><div className="detail-source"><span className={`source-badge ${signal.sourceType}`}>{sourceIcon(signal.sourceType)} {signal.kind}</span><span>{signal.source} · {signal.time}</span></div><h2>{signal.title}</h2><p className="detail-summary">{signal.summary}</p><div className="detail-score"><div><span>PROFILE MATCH</span><b>{signal.score}<small>/100</small></b></div><div className="score-bar"><i style={{ width: `${signal.score}%` }} /></div></div><div className="detail-block"><div className="detail-icon"><Sparkles size={16} /></div><div><b>Why you&apos;re seeing this</b><p>{signal.why}</p></div></div><div className="detail-block"><div className="detail-icon green"><ArrowUpRight size={16} /></div><div><b>What to do next</b><p>{signal.action}</p></div></div><div className="citation"><ShieldCheck size={16} /><div><b>Source citation</b><a href={signal.url} target="_blank" rel="noreferrer">{signal.source} — open original source <ExternalLink size={13} /></a></div></div><div className="detail-actions"><button className="primary-button small" onClick={onSave}><Bookmark size={15} /> Save to collection</button><button className="outline-button small" onClick={onClose}>Done</button></div></section></div>; }

function AskDock({ question, setQuestion, answer, asking, onAsk }: { question: string; setQuestion: (value: string) => void; answer: { text: string; sources: Array<{ title: string; source: string; url: string }> } | null; asking: boolean; onAsk: () => void }) { const [open, setOpen] = useState(false); return <div className={`ask-dock ${open ? "open" : ""}`}><button className="ask-trigger" onClick={() => setOpen(!open)}><span className="ask-trigger-icon"><MessageSquareText size={16} /></span><span><b>Ask SignalStack</b><small>Grounded in your sources</small></span><ChevronRight size={17} className="ask-chevron" /></button>{open && <div className="ask-popover"><div className="ask-popover-header"><div><div className="eyebrow">GROUNDED ANSWERS</div><h3>Ask your technical sources.</h3></div><button onClick={() => setOpen(false)} aria-label="Close"><X size={17} /></button></div><p>Retrieve supporting papers, repositories, releases, and engineering articles before answering.</p><textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="How should I make an AI-agent workflow more reliable?" /><button className="primary-button" onClick={onAsk} disabled={asking}>{asking ? "Retrieving evidence…" : "Ask SignalStack"}<ArrowUpRight size={15} /></button>{answer && <div className="ask-answer"><span><Check size={14} /> Retrieved answer</span><p>{answer.text}</p>{answer.sources.length > 0 && <div className="answer-sources">{answer.sources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.title}>{source.source}: {source.title} <ExternalLink size={12} /></a>)}</div>}</div>}</div>}</div>; }
